/*
Problem 389. Find the Difference

Problem Statement:

You are given two strings s and t.

String t is generated by randomly shuffling string s and adding one
extra letter at a random position.

Return the extra letter.

--------------------------------------------------

Intuition:

Since t contains all the characters of s plus exactly one additional
character, we can compare the frequency of every letter in both strings.

The extra character will be the one whose frequency remains 1 after
subtracting the frequencies of s from t.

Because the strings contain only lowercase English letters, a frequency
array of size 26 is sufficient.

--------------------------------------------------

Key Idea:

Step 1: Count the frequency of every character in t.
Step 2: Subtract the frequency of every character in s.
Step 3: The character whose final frequency is 1 is the extra character.
Step 4: Return that character.

--------------------------------------------------

Approach:

1. Create a frequency array of size 26 initialized with zeros.
2. Traverse string t and increment the count of each character.
3. Traverse string s and decrement the count of each character.
4. Traverse the frequency array.
5. The index whose frequency is 1 corresponds to the extra character.
6. Convert the index back to its character and return it.

--------------------------------------------------

Example:

Input:

s = "abcd"
t = "abcde"

Frequency after processing t:

a → 1
b → 1
c → 1
d → 1
e → 1

Subtract frequencies of s:

a → 0
b → 0
c → 0
d → 0
e → 1

The remaining frequency is:

e → 1

Output:
'e'

--------------------------------------------------

Counter Example:

Input:

s = ""
t = "y"

Frequency:

y → 1

There are no characters in s to subtract.

The remaining character is:

y

Output:
'y'

--------------------------------------------------

Why This Works:

Both strings contain the same characters except for one additional
character in t.

Adding the frequencies of t and subtracting the frequencies of s
cancels out every matching character.

Only the extra character remains with a frequency of 1.

--------------------------------------------------

Time Complexity: O(n)

Where:
- n = length of the longer string.

Both strings are traversed once, followed by a constant-size traversal
of the frequency array.

--------------------------------------------------

Space Complexity: O(1)

The frequency array always contains exactly 26 elements.

--------------------------------------------------

Pattern Used:
Hashing / Frequency Counting

Key Learning:

1. Frequency arrays are ideal when working with a fixed character set.
2. Incrementing for one string and decrementing for another effectively highlights differences.
3. Cancelling frequencies is a common technique for comparing two strings.
4. A fixed-size array provides constant-space complexity regardless of input size.
*/

class Solution {
public:
    char findTheDifference(string s, string t) {

        vector<int> freq(26, 0);

        // Step 1: Count frequencies in t
        for(char c : t)
        {
            freq[c - 'a']++;
        }

        // Step 2: Remove frequencies from s
        for(char c : s)
        {
            freq[c - 'a']--;
        }

        // Step 3: Find the extra character
        for(int i = 0; i < 26; i++)
        {
            if(freq[i] == 1)
            {
                return i + 'a';
            }
        }

        return ' ';
    }
};
